### ISSUE TITLE
Interviewbot responses "Sorry, that is incorrect" for answers that seems to be correct

### ISSUE THREAD

**Issue by jasonliang-dev** [noops-challenge/interviewbot#1]
I received the following question from Interviewbot:
```json
{
  "questionPath": "...",
  "question": "seventeen times eighty-eight divided by ninety-five minus thirty-three plus  ninety-seven plus  eighty-seven minus sixty-two",
  "message": "Please compute the numeric value of seventeen times eighty-eight divided by ninety-five minus thirty-three plus  ninety-seven plus  eighty-seven minus sixty-two. Note that, like most programming languages, multiplication and division have higher precedence than addition and subtraction",
  "exampleResponse": { "answer": 300 }
}
```

To numbers, that's: **17 * 88 / 95 - 33 + 97 + 87 - 62**

I've tried to answer with `104`, `105`, `104.74736842105261`, `104.74736842105263`, `104.7473684210526315789473684210526315789473684210526315789`, and even the string `"9951/95"`. All of these answers give me the same response:

```json
{
  "message": "Sorry, that is incorrect",
  "result": "incorrect"
}
```

I've also tried answering in words: `"nine thousand nine hundred fifty-one divided by ninety-five"`
```json
{
  "message": "Please provide your answer as a number",
  "result": "incorrect"
}
```

What's going on here? `104.74736842105261` seems to be the most reasonable answer. I've tried `"9951/95"` because that's the exact value. The decimal representation is non-terminating: 104.7**473684210526315789** (The repeating digits are in bold).

**Comment by davidmfoley** [comment]
Thanks for the report! This is now fixed.

The numeric form (`{ "answer": 104.747...}`) is the correct way to submit the answer -- there was a bug with checking the answer.
